# Generated by Django 4.2.7 on 2023-11-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('publisher', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('1', '1st to 4th grade'), ('2', '5th to 7th grade'), ('3', '8th to 10th grade'), ('4', 'Junior College'), ('5', 'Under Graduate'), ('6', 'Post Graduate'), ('7', 'PHD'), ('8', 'Miscellaneous')], max_length=20)),
                ('subcategory', models.CharField(choices=[('1', 'English'), ('2', 'Maths'), ('3', 'Science'), ('4', 'History'), ('5', 'Geography'), ('6', 'Marathi'), ('7', 'Hindi')], max_length=20)),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
